name: CI

on:
  push:
    branches:
      - main
      - case-key-paths
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-swift-latest:
    name: Library
    runs-on: macos-13
    strategy:
      matrix:
        config:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Run ${{ matrix.config }} tests
        run: make CONFIG=${{ matrix.config }} test-library

  library-windows:
    name: Library (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.8-release
          tag: 5.8-RELEASE
      - name: Build and test
        run: swift test

  library-evolution:
    name: Library (evolution)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Build for library evolution
        run: make build-for-library-evolution

  benchmarks:
    name: Benchmarks
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Run benchmark
        run: make benchmark

  examples:
    name: Examples
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Run tests
        run: make test-examples
